//
// Created by daria on 25/03/2021.
//

#ifndef A45_911_ANDRIOAIE_DARIA_ADMINSERVICETESTS_H
#define A45_911_ANDRIOAIE_DARIA_ADMINSERVICETESTS_H

#endif //A45_911_ANDRIOAIE_DARIA_ADMINSERVICETESTS_H

void run_all_admin_service_tests();