//
// Created by daria on 22/03/2021.
//

#ifndef A45_911_ANDRIOAIE_DARIA_DYNAMICARRAYTESTS_H
#define A45_911_ANDRIOAIE_DARIA_DYNAMICARRAYTESTS_H

#endif //A45_911_ANDRIOAIE_DARIA_DYNAMICARRAYTESTS_H

void run_all_dynamic_array_tests();